language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "iojs"
sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: false

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info

